services:
  db:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./sqlfiles/:/docker-entrypoint-initdb.d/
    ports:
      - 3306:3306

  server:
    image: nodejs
    volumes:
      - ./server:/server
      - /server/node_modules
    build:
      context: .
      dockerfile: ./server/Dockerfile
    restart: always
    ports:
      - 8000:8000
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_ROOT_PASSWORD
      - PORT=8000
    depends_on:
      - db
    command: node server.js

  # react:
  #   image: react
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   restart: always
  #   ports:
  #     - 5173:5173
  #   environment:
  #     - PORT=8000
  #   depends_on:
  #     - server

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
