services:
  react:
    image: react
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 5173:5173
    environment:
      - VITE_API_URL
    depends_on:
      - server
