name: Build, Test and Deploy React Application
# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]
# A workflow run is made up of one ore more jobs that can run sequentially or in parallel
jobs:
  build_test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: |
          npm install --silent
          npm run typedoc
          npm run build
          npm test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3

      - name: Build the stack
        run: docker-compose up -d

      - name: Run e2e tests with cypress
        uses: cypress-io/github-action@v6

      - name: Stop the stack
        run: docker-compose down

      - name: Upload artifcat
        uses: actions/upload-pages-artifact@v2
        with:
          # Upload entire repository
          path: ./dist
          if-no-files-found: error

  # Deploy job
  deploy:
    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    # Grant GITHUB_TOKEN the permissions required to make a page deployment
    permissions:
      pages: write
      id-token: write
    needs: build_test
    steps:
      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v2
